### ISSUE TITLE
La etiqueta header esta mal cerrada

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/ejercicios2020-juanfolco#1]
El archivo index.html no esta correcdtament

**Comment by juanfolco** [comment]
Buenas, profe, no estoy seguro de si fue un accidente, pero no veo el issue en el archivo que dice... Al menos al abrirlo se visualiza correctamente.

**Comment by edme88** [comment]
Hola Juan!

Perdón, necesitaba usar un repositorio de ejemplo, para mostrar como se
crean los tickets/issues en un repositorio (porque así es como les voy a
corregir cuando ustedes hagan el proyecto). Perdón! Justo entre al
classroom y tu proyecto era el primero que salia. 😓
Tu código está bien.

Saludos!

______________________
*Agustina Edmé Aliciardi*
Ing. en Computación
