### ISSUE TITLE
Falta agregar type="button" al elemento boton

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/ejercicios2020-juanfolco#3]
En la siguiente linea de código:
https://github.com/UCC-LabCompu2/ejercicios2020-juanfolco/blob/728663696ecfffb55154ba29a63eba052aa6d504/Ejercicios-JavaScript/canvas_x-y.html#L23

Es necesario agregarle el  **type="button"** al elemento

El código queria quedar:
`<button type="button" onclick="dibujarImage(inp_x.value, inp_y.value)"> `

**Comment by juanfolco** [comment]
¡Muchas gracias!
